#!/bin/bash
#
# run the GenDeck program to obtain a CIG SVN version ConMan set of input files
#
model=${1-new} 			# model name
rayleigh=${2-1e5}		# Rayleigh number
nelz=${3-30}			# number of elements in z
nsteps=${4-1000}		# number of timesteps
aspect=${5-1}			# aspect ratio, determines x width
heating=${6-0}			# internal heating
activationE=${7-0}		# activation energy
gdbin=${8-~becker/progs/src/cig/ConMan/src/gendeck/} # gendeck binary location

nelx=`echo $nelz $aspect | gawk '{x=int($1*$2);if(x%2!=0)x--;print(x)}'` # number of elements in x

version=1			# 1: standard ConMan
temp_ic=0			# temperature init, 0: conductive
restart="y"			# write restart file?
refactor_stiffness="y"		# allow for changes in viscosity 
wrap_around_bc="n"

nstep_restart=`echo $nsteps | gawk '{print(int($1/3))}'` # when to print restart files?
nstep_field=`echo $nsteps | gawk '{print(int($1/30))}'`  # for velocity and temp field output
nstep_stress=10000				    # for stress field output

ndtime_print=1.0		# non-dim time to print results

solver_type=1 # 0: banded 1: skyline

tbot=1				# temp BCs
ttop=0

# free slip BCs are asummed, that's the eight y after nstep_field
tperturbation=0.05
nmaterial=1
#  material 1 settings
ref_visc=1			# reference viscosity
penalty=1e7			# for incompressibility constraint
therm_diff=1			# thermal diffusivity

tempoff=0			# temperature offset
activationV=0			# activation volume
referencex2=0			# 
ref_stress=1			# reference stress
visc_max=1e3			# viscosity cutoff


echo $0: running gendeck. total timestep: $nstep field output spacing: $nstep_field
echo $0: resolution: $nelx by $nelz elements aspect ratio $aspect
echo $0: Rayleigh number $rayleigh


verbose=0			# 0 terse 1 verbose 2 terse with init

cat <<EOF > gendeck.in
$version

$model
Automatically generated with GenDeck
$nelx
$nelz
$verbose
y
$temp_ic
$restart
$refactor_stiffness
$wrap_around_bc
$solver_type
$nsteps
$ndtime_print
1.0
$nstep_restart
$nstep_field
$nstep_stress
y
y
y
y
y
y
y
y
$tperturbation
0
$aspect
0
1
$nmaterial
0
$ref_visc
$penalty
$therm_diff
$rayleigh
$heating
$activationE
$tempoff
$activationV
$referencex2
$visc_max
n
$tbot
$ttop
EOF

$gdbin/GenDeck < gendeck.in

