#
# makefile for the grid library
# 
FC=ifort
FFLAGS = -O2

GRID=genBC.o genfl12.o genfl.o geniBC.o genNBC.o iclear_mov.o move.o smove.o clear.o

#
../libs/libgrid.a: $(GRID)
	$(AR) cr ../libs/libgrid.a  $(GRID) 

clean:
	rm -rf core $(GRID) 

