#
# makefile for the memory manager library
# 
FC=gfortran
FFLAGS=-O2 -fcray-pointer
CFLAGS=
CC=gcc

MEMORY_MANAGER=mmsc.o mm2000.o

../libs/libmm.a: $(MEMORY_MANAGER)
	$(AR) cr ../libs/libmm.a  $(MEMORY_MANAGER) 

#
../libs/libmm.a: $(MEMORY_MANAGER)

clean:
	rm -rf core $(MEMORY_MANAGER) 

