#
# makefile for the memory manager library
# 
FC=ifort
FFLAGS=-O2 
CFLAGS= 
#CC=gcc 
CC=icc

MEMORY_MANAGER=mmsc.o mm2000.o driver.o
../libs/libmm.a: $(MEMORY_MANAGER)
	$(AR) cr ../libs/libmm.a  $(MEMORY_MANAGER) 

../libs/libmm.a: $(MEMORY_MANAGER)


driver: $(MEMORY_MANAGER)
	$(FC) $(MEMORY_MANAGER) -o driver

#
clean:
	rm -rf core $(MEMORY_MANAGER) 

