#
# makefile for the memory manager library
# 
FC=ifort
FFLAGS=-O2 -m64 -r8 -i8
CFLAGS= 
CC=gcc -m64  -DMMSC_INT_TYPE=int64_t

MEMORY_MANAGER=mmsc.o mm2000.o driver.o

driver: $(MEMORY_MANAGER)
	$(FC) $(MEMORY_MANAGER) -o driver

#
clean:
	rm -rf core $(MEMORY_MANAGER) 

