#
# makefile for the memory manager library
# 
FC=ifort
FFLAGS=-O2 
CFLAGS= 
CC=gcc 

MEMORY_MANAGER=mmsc.o mm2000.o driver.o

driver: $(MEMORY_MANAGER)
	$(FC) $(MEMORY_MANAGER) -o driver

#
clean:
	rm -rf core $(MEMORY_MANAGER) 

