C--THESE ARE THE VERTEX COORDS IN DECIMAL DEGREES
      DATA PY(  1),PX(  1) /38.8350,-122.9883/
      DATA PY(  2),PX(  2) /38.9267,-122.8200/
      DATA PY(  3),PX(  3) /38.6833,-122.8400/
      DATA PY(  4),PX(  4) /38.7700,-122.6800/
      DATA PY(  5),PX(  5) /38.9250,-122.3967/
      DATA PY(  6),PX(  6) /37.7950,-122.7317/
      DATA PY(  7),PX(  7) /37.8783,-122.5750/
      DATA PY(  8),PX(  8) /37.9600,-122.4250/
      DATA PY(  9),PX(  9) /37.9867,-122.3800/
      DATA PY( 10),PX( 10) /38.0150,-122.3267/
      DATA PY( 11),PX( 11) /38.0633,-122.2433/
      DATA PY( 12),PX( 12) /38.1300,-122.1167/
      DATA PY( 13),PX( 13) /38.1600,-122.0567/
      DATA PY( 14),PX( 14) /38.1967,-121.9900/
      DATA PY( 15),PX( 15) /37.3500,-122.5300/
      DATA PY( 16),PX( 16) /37.4117,-122.4117/
      DATA PY( 17),PX( 17) /37.5017,-122.2367/
      DATA PY( 18),PX( 18) /37.7667,-122.0883/
      DATA PY( 19),PX( 19) /37.8683,-121.9033/
      DATA PY( 20),PX( 20) /37.2933,-122.3117/
      DATA PY( 21),PX( 21) /37.4233,-122.1633/
      DATA PY( 22),PX( 22) /37.5167,-121.9917/
      DATA PY( 23),PX( 23) /37.5650,-121.9000/
      DATA PY( 24),PX( 24) /37.6300,-121.7800/
      DATA PY( 25),PX( 25) /37.7333,-121.5900/
      DATA PY( 26),PX( 26) /36.9567,-122.3317/
      DATA PY( 27),PX( 27) /37.1167,-122.0650/
      DATA PY( 28),PX( 28) /37.1983,-121.9600/
      DATA PY( 29),PX( 29) /37.4167,-121.8967/
      DATA PY( 30),PX( 30) /37.4783,-121.7933/
      DATA PY( 31),PX( 31) /37.5017,-121.7433/
      DATA PY( 32),PX( 32) /37.2983,-121.7767/
      DATA PY( 33),PX( 33) /37.3683,-121.6400/
      DATA PY( 34),PX( 34) /36.9383,-121.8167/
      DATA PY( 35),PX( 35) /37.0450,-121.7017/
      DATA PY( 36),PX( 36) /37.1517,-121.6400/
      DATA PY( 37),PX( 37) /37.2167,-121.5233/
      DATA PY( 38),PX( 38) /37.0667,-121.5583/
      DATA PY( 39),PX( 39) /37.1183,-121.4500/
      DATA PY( 40),PX( 40) /36.5567,-122.1333/
      DATA PY( 41),PX( 41) /36.6767,-121.9000/
      DATA PY( 42),PX( 42) /36.8100,-121.6400/
      DATA PY( 43),PX( 43) /36.8750,-121.5483/
      DATA PY( 44),PX( 44) / 0.0000,   0.0000/
      DATA PY( 45),PX( 45) /36.9517,-121.4650/
      DATA PY( 46),PX( 46) /36.9667,-121.3933/
      DATA PY( 47),PX( 47) /37.0400,-121.3917/
      DATA PY( 48),PX( 48) /37.0650,-121.3450/
      DATA PY( 49),PX( 49) /37.1867,-121.1233/
      DATA PY( 50),PX( 50) /36.8383,-121.4850/
      DATA PY( 51),PX( 51) /36.8917,-121.4367/
      DATA PY( 52),PX( 52) /36.8567,-121.3583/
      DATA PY( 53),PX( 53) /36.6750,-121.4500/
      DATA PY( 54),PX( 54) /36.7417,-121.3667/
      DATA PY( 55),PX( 55) /36.7700,-121.3333/
      DATA PY( 56),PX( 56) /36.5700,-121.3083/
      DATA PY( 57),PX( 57) /36.6367,-121.2033/
      DATA PY( 58),PX( 58) /36.6883,-121.1300/
      DATA PY( 59),PX( 59) /36.4633,-121.1667/
      DATA PY( 60),PX( 60) /36.5467,-121.0233/
      DATA PY( 61),PX( 61) /36.5733,-120.9750/
      DATA PY( 62),PX( 62) /36.7633,-120.6167/
      DATA PY( 63),PX( 63) /35.8417,-121.7833/
      DATA PY( 64),PX( 64) /36.1067,-121.2967/
      DATA PY( 65),PX( 65) /36.2833,-120.9667/
      DATA PY( 66),PX( 66) /36.4333,-120.9367/
      DATA PY( 67),PX( 67) /36.5217,-121.0700/
      DATA PY( 68),PX( 68) /36.2400,-120.7200/
      DATA PY( 69),PX( 69) /36.5167,-120.3300/
      DATA PY( 70),PX( 70) /36.0967,-120.7617/
      DATA PY( 71),PX( 71) /36.1750,-120.6500/
      DATA PY( 72),PX( 72) /35.9667,-120.6333/
      DATA PY( 73),PX( 73) /36.0250,-120.4917/
      DATA PY( 74),PX( 74) /35.8667,-120.5250/
      DATA PY( 75),PX( 75) /35.9500,-120.4167/
      DATA PY( 76),PX( 76) /35.5883,-120.2133/
      DATA PY( 77),PX( 77) /35.6667,-120.0983/
      DATA PY( 78),PX( 78) /35.9633,-119.6900/
      DATA PY( 79),PX( 79) /34.8433,-120.9417/
      DATA PY( 80),PX( 80) /35.1550,-120.4050/
      DATA PY( 81),PX( 81) /35.3600,-119.8500/
      DATA PY( 82),PX( 82) /41.7850,-123.9617/
      DATA PY( 83),PX( 83) /41.8917,-123.3133/
      DATA PY( 84),PX( 84) /42.0000,-122.6883/
      DATA PY( 85),PX( 85) /40.5933,-125.8883/
      DATA PY( 86),PX( 86) /40.5417,-125.1617/
      DATA PY( 87),PX( 87) /41.3867,-123.7800/
      DATA PY( 88),PX( 88) /40.2317,-125.9183/
      DATA PY( 89),PX( 89) /40.3950,-123.3300/
      DATA PY( 90),PX( 90) /40.1017,-124.1767/
      DATA PY( 91),PX( 91) /40.0817,-123.9067/
      DATA PY( 92),PX( 92) /40.0500,-123.5817/
      DATA PY( 93),PX( 93) /40.0217,-123.1633/
      DATA PY( 94),PX( 94) /39.9917,-122.0667/
      DATA PY( 95),PX( 95) /40.4417,-121.6567/
      DATA PY( 96),PX( 96) /40.5333,-121.5083/
      DATA PY( 97),PX( 97) /40.3167,-121.5217/
      DATA PY( 98),PX( 98) /40.4067,-121.3717/
      DATA PY( 99),PX( 99) /40.5683,-121.0883/
      DATA PY(100),PX(100) /39.5517,-121.7950/
      DATA PY(101),PX(101) /39.7383,-121.4000/
      DATA PY(102),PX(102) /40.1183,-120.6000/
      DATA PY(103),PX(103) /39.1700,-121.5850/
      DATA PY(104),PX(104) /39.3867,-120.9817/
      DATA PY(105),PX(105) /39.0400,-123.9633/
      DATA PY(106),PX(106) /38.5517,-123.4750/
      DATA PY(107),PX(107) /38.7733,-123.0800/
      DATA PY(108),PX(108) /39.0250,-122.7050/
      DATA PY(109),PX(109) /38.8450,-122.5450/
      DATA PY(110),PX(110) /38.4533,-121.2133/
      DATA PY(111),PX(111) /38.7333,-120.2000/
      DATA PY(112),PX(112) /37.4550,-120.2500/
      DATA PY(113),PX(113) /38.0167,-119.3700/
      DATA PY(114),PX(114) /38.7117,-118.4667/
      DATA PY(115),PX(115) /36.3283,-119.1900/
      DATA PY(116),PX(116) /36.9950,-121.7550/
      DATA PY(117),PX(117) /37.9750,-118.3167/
      DATA PY(118),PX(118) /37.9417,-119.1583/
      DATA PY(119),PX(119) /34.0000,-131.0000/
      DATA PY(120),PX(120) /37.9417,-118.9833/
      DATA PY(121),PX(121) /37.8833,-118.8167/
      DATA PY(122),PX(122) /37.8833,-118.5500/
      DATA PY(123),PX(123) /37.8417,-118.4333/
      DATA PY(124),PX(124) / 0.0000,   0.0000/
      DATA PY(125),PX(125) /37.8000,-119.0417/
      DATA PY(126),PX(126) /37.8000,-118.9833/
      DATA PY(127),PX(127) /37.7583,-118.9833/
      DATA PY(128),PX(128) /36.6250,-118.2250/
      DATA PY(129),PX(129) / 0.0000,   0.0000/
      DATA PY(130),PX(130) /39.7217,-120.0000/
      DATA PY(131),PX(131) /42.0000,-120.0000/
      DATA PY(132),PX(132) /44.0000,-134.0000/
      DATA PY(133),PX(133) /46.0000,-124.0000/
      DATA PY(134),PX(134) /46.0000,-117.0000/
      DATA PY(135),PX(135) /42.0000,-114.0000/
      DATA PY(136),PX(136) /33.0000,-113.0000/
      DATA PY(137),PX(137) /32.0000,-118.0000/
      DATA PY(138),PX(138) /30.0000,-127.0000/
      DATA PY(139),PX(139) /37.7583,-118.8167/
      DATA PY(140),PX(140) /37.7583,-118.7750/
      DATA PY(141),PX(141) /37.7250,-118.9167/
      DATA PY(142),PX(142) /37.7250,-118.8583/
      DATA PY(143),PX(143) /37.7250,-118.7000/
      DATA PY(144),PX(144) /37.6883,-118.8283/
      DATA PY(145),PX(145) /37.6783,-118.9417/
      DATA PY(146),PX(146) /37.6667,-119.0833/
      DATA PY(147),PX(147) /37.6667,-119.0417/
      DATA PY(148),PX(148) /37.6667,-118.9833/
      DATA PY(149),PX(149) /37.6583,-118.7000/
      DATA PY(150),PX(150) /37.6583,-118.5733/
      DATA PY(151),PX(151) /37.6500,-118.9167/
      DATA PY(152),PX(152) /37.6500,-118.8583/
      DATA PY(153),PX(153) /37.6200,-118.9833/
      DATA PY(154),PX(154) /37.6200,-118.8833/
      DATA PY(155),PX(155) /37.6000,-119.0833/
      DATA PY(156),PX(156) /37.6000,-118.9833/
      DATA PY(157),PX(157) /37.6000,-118.8917/
      DATA PY(158),PX(158) /37.6000,-118.8500/
      DATA PY(159),PX(159) /37.6000,-118.8250/
      DATA PY(160),PX(160) /37.6000,-118.7750/
      DATA PY(161),PX(161) /37.5167,-118.6500/
      DATA PY(162),PX(162) /37.5167,-118.5500/
      DATA PY(163),PX(163) /37.5167,-118.5000/
      DATA PY(164),PX(164) /37.4917,-117.8750/
      DATA PY(165),PX(165) /37.4333,-118.8917/
      DATA PY(166),PX(166) /37.4333,-118.7750/
      DATA PY(167),PX(167) /37.3833,-119.1583/
      DATA PY(168),PX(168) /37.3833,-118.7750/
      DATA PY(169),PX(169) /37.3833,-118.6500/
      DATA PY(170),PX(170) /37.3833,-118.5500/
      DATA PY(171),PX(171) /37.3833,-118.4167/
      DATA PY(172),PX(172) /37.3833,-118.3000/
      DATA PY(173),PX(173) / 0.0000,   0.0000/
      DATA PY(174),PX(174) / 0.0000,   0.0000/
      DATA PY(175),PX(175) / 0.0000,   0.0000/
      DATA PY(176),PX(176) /37.2333,-118.2583/
      DATA PY(177),PX(177) / 0.0000,   0.0000/
      DATA PY(178),PX(178) / 0.0000,   0.0000/
      DATA PY(179),PX(179) / 0.0000,   0.0000/
      DATA PY(180),PX(180) /37.6000,-119.1583/
      DATA PY(181),PX(181) / 0.0000,   0.0000/
      DATA PY(182),PX(182) / 0.0000,   0.0000/
      DATA PY(183),PX(183) / 0.0000,   0.0000/
      DATA PY(184),PX(184) / 0.0000,   0.0000/
      DATA PY(185),PX(185) / 0.0000,   0.0000/
      DATA PY(186),PX(186) / 0.0000,   0.0000/
      DATA PY(187),PX(187) / 0.0000,   0.0000/
      DATA PY(188),PX(188) / 0.0000,   0.0000/
      DATA PY(189),PX(189) /36.7833,-116.9167/
      DATA PY(190),PX(190) / 0.0000,   0.0000/
      DATA PY(191),PX(191) / 0.0000,   0.0000/
      DATA PY(192),PX(192) / 0.0000,   0.0000/
      DATA PY(193),PX(193) /36.6083,-118.0000/
      DATA PY(194),PX(194) /35.5583,-117.8667/
      DATA PY(195),PX(195) /35.4167,-117.4450/
      DATA PY(196),PX(196) /34.7600,-118.5633/
      DATA PY(197),PX(197) /34.8533,-118.9883/
      DATA PY(198),PX(198) /34.9800,-119.4183/
      DATA PY(199),PX(199) /34.0833,-119.0450/
      DATA PY(200),PX(200) /34.1017,-120.6383/
      DATA PY(201),PX(201) /36.4333,-118.0333/
      DATA PY(202),PX(202) /36.4250,-117.8000/
      DATA PY(203),PX(203) / 0.0000,   0.0000/
      DATA PY(204),PX(204) / 0.0000,   0.0000/
      DATA PY(205),PX(205) / 0.0000,   0.0000/
      DATA PY(206),PX(206) /36.3417,-117.7000/
      DATA PY(207),PX(207) /36.3417,-117.5583/
      DATA PY(208),PX(208) / 0.0000,   0.0000/
      DATA PY(209),PX(209) / 0.0000,   0.0000/
      DATA PY(210),PX(210) / 0.0000,   0.0000/
      DATA PY(211),PX(211) /36.2917,-116.2667/
      DATA PY(212),PX(212) / 0.0000,   0.0000/
      DATA PY(213),PX(213) / 0.0000,   0.0000/
      DATA PY(214),PX(214) / 0.0000,   0.0000/
      DATA PY(215),PX(215) / 0.0000,   0.0000/
      DATA PY(216),PX(216) /36.1417,-118.0333/
      DATA PY(217),PX(217) / 0.0000,   0.0000/
      DATA PY(218),PX(218) / 0.0000,   0.0000/
      DATA PY(219),PX(219) / 0.0000,   0.0000/
      DATA PY(220),PX(220) / 0.0000,   0.0000/
      DATA PY(221),PX(221) /35.9000,-117.9000/
      DATA PY(222),PX(222) /35.8833,-117.4317/
      DATA PY(223),PX(223) / 0.0000,   0.0000/
      DATA PY(224),PX(224) / 0.0000,   0.0000/
      DATA PY(225),PX(225) / 0.0000,   0.0000/
      DATA PY(226),PX(226) /35.7333,-116.0000/
      DATA PY(227),PX(227) / 0.0000,   0.0000/
      DATA PY(228),PX(228) /35.7000,-117.4000/
      DATA PY(229),PX(229) / 0.0000,   0.0000/
      DATA PY(230),PX(230) / 0.0000,   0.0000/
      DATA PY(231),PX(231) / 0.0000,   0.0000/
      DATA PY(232),PX(232) / 0.0000,   0.0000/
      DATA PY(233),PX(233) /35.6167,-116.3500/
      DATA PY(234),PX(234) /35.5833,-117.0417/
      DATA PY(235),PX(235) / 0.0000,   0.0000/
      DATA PY(236),PX(236) / 0.0000,   0.0000/
      DATA PY(237),PX(237) / 0.0000,   0.0000/
      DATA PY(238),PX(238) / 0.0000,   0.0000/
      DATA PY(239),PX(239) /36.0000,-117.4667/
      DATA PY(240),PX(240) / 0.0000,   0.0000/
      DATA PY(241),PX(241) / 0.0000,   0.0000/
      DATA PY(242),PX(242) /36.0167,-116.0000/

C--FOR EACH REGION, DEFINE ITS NAME, POINTER TO FIRST
C--VERTEX, AND ORDERED LIST OF VERTICIES
      DATA NAM(  1),NS(  1) /'SFP',  1/ !S.F. Peninsula           
      DATA FN(  1) /'S.F. Peninsula           '/
      DATA JVEX(  1) /  7/
      DATA JVEX(  2) / 17/
      DATA JVEX(  3) / 16/
      DATA JVEX(  4) /  6/
      DATA NAM(  2),NS(  2) /'BLM',  5/ !Black Mountain           
      DATA FN(  2) /'Black Mountain           '/
      DATA JVEX(  5) / 17/
      DATA JVEX(  6) / 21/
      DATA JVEX(  7) / 28/
      DATA JVEX(  8) / 27/
      DATA JVEX(  9) / 20/
      DATA JVEX( 10) / 16/
      DATA NAM(  3),NS(  3) /'LOM', 11/ !Loma Prieta              
      DATA FN(  3) /'Loma Prieta              '/
      DATA JVEX( 11) / 28/
      DATA JVEX( 12) / 35/
      DATA JVEX( 13) /116/
      DATA JVEX( 14) / 34/
      DATA JVEX( 15) / 27/
      DATA NAM(  4),NS(  4) /'SAR', 16/ !Sargent Fault            
      DATA FN(  4) /'Sargent Fault            '/
      DATA JVEX( 16) / 35/
      DATA JVEX( 17) / 45/
      DATA JVEX( 18) / 43/
      DATA JVEX( 19) /116/
      DATA NAM(  5),NS(  5) /'BUS', 20/ !Busch Fault              
      DATA FN(  5) /'Busch Fault              '/
      DATA JVEX( 20) / 45/
      DATA JVEX( 21) / 51/
      DATA JVEX( 22) / 50/
      DATA JVEX( 23) / 43/
      DATA NAM(  6),NS(  6) /'SJB', 24/ !San Juan Bautista        
      DATA FN(  6) /'San Juan Bautista        '/
      DATA JVEX( 24) /116/
      DATA JVEX( 25) / 43/
      DATA JVEX( 26) / 50/
      DATA JVEX( 27) / 54/
      DATA JVEX( 28) / 53/
      DATA JVEX( 29) / 42/
      DATA JVEX( 30) / 34/
      DATA NAM(  7),NS(  7) /'STN', 31/ !Stone Canyon             
      DATA FN(  7) /'Stone Canyon             '/
      DATA JVEX( 31) / 54/
      DATA JVEX( 32) / 57/
      DATA JVEX( 33) / 56/
      DATA JVEX( 34) / 53/
      DATA NAM(  8),NS(  8) /'PIN', 35/ !Pinnacles                
      DATA FN(  8) /'Pinnacles                '/
      DATA JVEX( 35) / 57/
      DATA JVEX( 36) / 67/
      DATA JVEX( 37) / 59/
      DATA JVEX( 38) / 56/
      DATA NAM(  9),NS(  9) /'HOL', 39/ !Hollister                
      DATA FN(  9) /'Hollister                '/
      DATA JVEX( 39) / 46/
      DATA JVEX( 40) / 52/
      DATA JVEX( 41) / 55/
      DATA JVEX( 42) / 54/
      DATA JVEX( 43) / 50/
      DATA JVEX( 44) / 51/
      DATA JVEX( 45) / 45/
      DATA NAM( 10),NS( 10) /'PAI', 46/ !Paicines                 
      DATA FN( 10) /'Paicines                 '/
      DATA JVEX( 46) / 52/
      DATA JVEX( 47) / 58/
      DATA JVEX( 48) / 57/
      DATA JVEX( 49) / 54/
      DATA JVEX( 50) / 55/
      DATA NAM( 11),NS( 11) /'BVL', 51/ !Bear Valley              
      DATA FN( 11) /'Bear Valley              '/
      DATA JVEX( 51) / 58/
      DATA JVEX( 52) / 60/
      DATA JVEX( 53) / 67/
      DATA JVEX( 54) / 57/
      DATA NAM( 12),NS( 12) /'BIT', 55/ !Bitterwater Valley       
      DATA FN( 12) /'Bitterwater Valley       '/
      DATA JVEX( 55) / 60/
      DATA JVEX( 56) / 66/
      DATA JVEX( 57) / 68/
      DATA JVEX( 58) / 71/
      DATA JVEX( 59) / 70/
      DATA JVEX( 60) / 65/
      DATA JVEX( 61) / 59/
      DATA JVEX( 62) / 67/
      DATA NAM( 13),NS( 13) /'SLA', 63/ !Slack Canyon             
      DATA FN( 13) /'Slack Canyon             '/
      DATA JVEX( 63) / 71/
      DATA JVEX( 64) / 73/
      DATA JVEX( 65) / 72/
      DATA JVEX( 66) / 70/
      DATA NAM( 14),NS( 14) /'MID', 67/ !Middle Mountain          
      DATA FN( 14) /'Middle Mountain          '/
      DATA JVEX( 67) / 73/
      DATA JVEX( 68) / 75/
      DATA JVEX( 69) / 74/
      DATA JVEX( 70) / 72/
      DATA NAM( 15),NS( 15) /'GOL', 71/ !Gold Hill                
      DATA FN( 15) /'Gold Hill                '/
      DATA JVEX( 71) / 75/
      DATA JVEX( 72) / 77/
      DATA JVEX( 73) / 76/
      DATA JVEX( 74) / 74/
      DATA NAM( 16),NS( 16) /'HAY', 75/ !Hayward Fault            
      DATA FN( 16) /'Hayward Fault            '/
      DATA JVEX( 75) / 10/
      DATA JVEX( 76) / 18/
      DATA JVEX( 77) / 23/
      DATA JVEX( 78) / 22/
      DATA JVEX( 79) /  8/
      DATA JVEX( 80) /  9/
      DATA NAM( 17),NS( 17) /'MIS', 81/ !Mission Fault            
      DATA FN( 17) /'Mission Fault            '/
      DATA JVEX( 81) / 23/
      DATA JVEX( 82) / 30/
      DATA JVEX( 83) / 29/
      DATA JVEX( 84) / 22/
      DATA NAM( 18),NS( 18) /'CON', 85/ !Concord Fault            
      DATA FN( 18) /'Concord Fault            '/
      DATA JVEX( 85) / 13/
      DATA JVEX( 86) / 19/
      DATA JVEX( 87) / 18/
      DATA JVEX( 88) / 10/
      DATA JVEX( 89) / 11/
      DATA JVEX( 90) / 12/
      DATA NAM( 19),NS( 19) /'DAN', 91/ !Danville                 
      DATA FN( 19) /'Danville                 '/
      DATA JVEX( 91) / 19/
      DATA JVEX( 92) / 24/
      DATA JVEX( 93) / 23/
      DATA JVEX( 94) / 18/
      DATA NAM( 20),NS( 20) /'SUN', 95/ !Sunol                    
      DATA FN( 20) /'Sunol                    '/
      DATA JVEX( 95) / 24/
      DATA JVEX( 96) / 31/
      DATA JVEX( 97) / 30/
      DATA JVEX( 98) / 23/
      DATA NAM( 21),NS( 21) /'ALU', 99/ !Alum Rock                
      DATA FN( 21) /'Alum Rock                '/
      DATA JVEX( 99) / 31/
      DATA JVEX(100) / 33/
      DATA JVEX(101) / 32/
      DATA JVEX(102) / 29/
      DATA JVEX(103) / 30/
      DATA NAM( 22),NS( 22) /'SFL',104/ !San Felipe               
      DATA FN( 22) /'San Felipe               '/
      DATA JVEX(104) / 33/
      DATA JVEX(105) / 37/
      DATA JVEX(106) / 36/
      DATA JVEX(107) / 32/
      DATA NAM( 23),NS( 23) /'CYN',108/ !Coyote North             
      DATA FN( 23) /'Coyote North             '/
      DATA JVEX(108) / 37/
      DATA JVEX(109) / 39/
      DATA JVEX(110) / 38/
      DATA JVEX(111) / 36/
      DATA NAM( 24),NS( 24) /'CYS',112/ !Coyote South             
      DATA FN( 24) /'Coyote South             '/
      DATA JVEX(112) / 39/
      DATA JVEX(113) / 46/
      DATA JVEX(114) / 45/
      DATA JVEX(115) / 38/
      DATA NAM( 25),NS( 25) /'QUI',116/ !Quiensabe                
      DATA FN( 25) /'Quiensabe                '/
      DATA JVEX(116) / 39/
      DATA JVEX(117) / 47/
      DATA JVEX(118) / 58/
      DATA JVEX(119) / 52/
      DATA JVEX(120) / 46/
      DATA NAM( 26),NS( 26) /'GRN',121/ !Greenville Fault         
      DATA FN( 26) /'Greenville Fault         '/
      DATA JVEX(121) / 14/
      DATA JVEX(122) / 25/
      DATA JVEX(123) / 24/
      DATA JVEX(124) / 19/
      DATA JVEX(125) / 13/
      DATA NAM( 27),NS( 27) /'HAM',126/ !Mt. Hamilton             
      DATA FN( 27) /'Mt. Hamilton             '/
      DATA JVEX(126) / 25/
      DATA JVEX(127) / 49/
      DATA JVEX(128) / 48/
      DATA JVEX(129) / 47/
      DATA JVEX(130) / 39/
      DATA JVEX(131) / 37/
      DATA JVEX(132) / 33/
      DATA JVEX(133) / 31/
      DATA JVEX(134) / 24/
      DATA NAM( 28),NS( 28) /'ORT',135/ !Ortigaleta Fault         
      DATA FN( 28) /'Ortigaleta Fault         '/
      DATA JVEX(135) / 49/
      DATA JVEX(136) / 62/
      DATA JVEX(137) / 61/
      DATA JVEX(138) / 48/
      DATA NAM( 29),NS( 29) /'PAN',139/ !Panoche Pass             
      DATA FN( 29) /'Panoche Pass             '/
      DATA JVEX(139) / 48/
      DATA JVEX(140) / 61/
      DATA JVEX(141) / 60/
      DATA JVEX(142) / 58/
      DATA JVEX(143) / 47/
      DATA NAM( 30),NS( 30) /'CRV',144/ !Ciervo Hills             
      DATA FN( 30) /'Ciervo Hills             '/
      DATA JVEX(144) / 62/
      DATA JVEX(145) / 69/
      DATA JVEX(146) / 68/
      DATA JVEX(147) / 66/
      DATA JVEX(148) / 60/
      DATA JVEX(149) / 61/
      DATA NAM( 31),NS( 31) /'COA',150/ !Coalinga                 
      DATA FN( 31) /'Coalinga                 '/
      DATA JVEX(150) / 69/
      DATA JVEX(151) / 78/
      DATA JVEX(152) / 77/
      DATA JVEX(153) / 75/
      DATA JVEX(154) / 73/
      DATA JVEX(155) / 71/
      DATA JVEX(156) / 68/
      DATA NAM( 32),NS( 32) /'SFB',157/ !South S.F. Bay           
      DATA FN( 32) /'South S.F. Bay           '/
      DATA JVEX(157) /  8/
      DATA JVEX(158) / 22/
      DATA JVEX(159) / 21/
      DATA JVEX(160) / 17/
      DATA JVEX(161) /  7/
      DATA NAM( 33),NS( 33) /'SCV',162/ !Santa Clara Valley       
      DATA FN( 33) /'Santa Clara Valley       '/
      DATA JVEX(162) / 22/
      DATA JVEX(163) / 29/
      DATA JVEX(164) / 32/
      DATA JVEX(165) / 36/
      DATA JVEX(166) / 38/
      DATA JVEX(167) / 45/
      DATA JVEX(168) / 35/
      DATA JVEX(169) / 28/
      DATA JVEX(170) / 21/
      DATA NAM( 34),NS( 34) /'ANN',171/ !Anno Nuevo               
      DATA FN( 34) /'Anno Nuevo               '/
      DATA JVEX(171) / 16/
      DATA JVEX(172) / 20/
      DATA JVEX(173) / 27/
      DATA JVEX(174) / 26/
      DATA JVEX(175) / 15/
      DATA NAM( 35),NS( 35) /'MON',176/ !Monterey Bay             
      DATA FN( 35) /'Monterey Bay             '/
      DATA JVEX(176) / 27/
      DATA JVEX(177) / 34/
      DATA JVEX(178) / 42/
      DATA JVEX(179) / 41/
      DATA JVEX(180) / 40/
      DATA JVEX(181) / 26/
      DATA NAM( 36),NS( 36) /'SAL',182/ !Salinas Valley           
      DATA FN( 36) /'Salinas Valley           '/
      DATA JVEX(182) / 42/
      DATA JVEX(183) / 53/
      DATA JVEX(184) / 56/
      DATA JVEX(185) / 59/
      DATA JVEX(186) / 65/
      DATA JVEX(187) / 64/
      DATA JVEX(188) / 41/
      DATA NAM( 37),NS( 37) /'SUR',189/ !Big Sur (Hosgri Fault)   
      DATA FN( 37) /'Big Sur (Hosgri Fault)   '/
      DATA JVEX(189) / 41/
      DATA JVEX(190) / 64/
      DATA JVEX(191) / 63/
      DATA JVEX(192) / 40/
      DATA NAM( 38),NS( 38) /'ROB',193/ !Paso Robles              
      DATA FN( 38) /'Paso Robles              '/
      DATA JVEX(193) / 65/
      DATA JVEX(194) / 70/
      DATA JVEX(195) / 72/
      DATA JVEX(196) / 74/
      DATA JVEX(197) / 76/
      DATA JVEX(198) / 80/
      DATA JVEX(199) / 64/
      DATA NAM( 39),NS( 39) /'SSM',200/ !San Simeon               
      DATA FN( 39) /'San Simeon               '/
      DATA JVEX(200) / 64/
      DATA JVEX(201) / 80/
      DATA JVEX(202) / 79/
      DATA JVEX(203) / 63/
      DATA NAM( 40),NS( 40) /'SIM',204/ !Simmler                  
      DATA FN( 40) /'Simmler                  '/
      DATA JVEX(204) / 77/
      DATA JVEX(205) / 81/
      DATA JVEX(206) / 80/
      DATA JVEX(207) / 76/
      DATA NAM( 41),NS( 41) /'MAR',208/ !Marin                    
      DATA FN( 41) /'Marin                    '/
      DATA JVEX(208) /107/
      DATA JVEX(209) /  9/
      DATA JVEX(210) /  8/
      DATA JVEX(211) /  7/
      DATA JVEX(212) /  6/
      DATA JVEX(213) /106/
      DATA NAM( 42),NS( 42) /'ROG',214/ !Rodgers Creek Fault       
      DATA FN( 42) /'Rodgers Creek Fault      '/
      DATA JVEX(214) /  1/
      DATA JVEX(215) /  3/
      DATA JVEX(216) / 11/
      DATA JVEX(217) / 10/
      DATA JVEX(218) /  9/
      DATA JVEX(219) /107/
      DATA NAM( 43),NS( 43) /'GEY',220/ !Geysers                  
      DATA FN( 43) /'Geysers                  '/
      DATA JVEX(220) /  2/
      DATA JVEX(221) /  4/
      DATA JVEX(222) /  3/
      DATA JVEX(223) /  1/
      DATA NAM( 44),NS( 44) /'KON',224/ !Konocti Bay              
      DATA FN( 44) /'Konocti Bay              '/
      DATA JVEX(224) /108/
      DATA JVEX(225) /109/
      DATA JVEX(226) /  4/
      DATA JVEX(227) /  2/
      DATA NAM( 45),NS( 45) /'NAP',228/ !West Napa Fault
      DATA FN( 45) /'West Napa Fault          '/
      DATA JVEX(228) /  4/
      DATA JVEX(229) / 12/
      DATA JVEX(230) / 11/
      DATA JVEX(231) /  3/
      DATA NAM( 46),NS( 46) /'GVL',232/ !Green Valley Fault       
      DATA FN( 46) /'Green Valley Fault       '/
      DATA JVEX(232) /  5/
      DATA JVEX(233) / 14/
      DATA JVEX(234) / 13/
      DATA JVEX(235) / 12/
      DATA JVEX(236) /  4/
      DATA JVEX(237) /109/
      DATA NAM( 47),NS( 47) /'PAR',238/ !Point Arena              
      DATA FN( 47) /'Point Arena              '/
      DATA JVEX(238) / 91/
      DATA JVEX(239) /107/
      DATA JVEX(240) /106/
      DATA JVEX(241) /105/
      DATA JVEX(242) / 90/
      DATA NAM( 48),NS( 48) /'MAA',243/ !Maacama Fault            
      DATA FN( 48) /'Maacama Fault            '/
      DATA JVEX(243) / 92/
      DATA JVEX(244) /  2/
      DATA JVEX(245) /  1/
      DATA JVEX(246) /107/
      DATA JVEX(247) / 91/
      DATA NAM( 49),NS( 49) /'BAR',248/ !Bartlett Springs Fault   
      DATA FN( 49) /'Bartlett Springs Fault   '/
      DATA JVEX(248) / 93/
      DATA JVEX(249) /  5/
      DATA JVEX(250) /109/
      DATA JVEX(251) /108/
      DATA JVEX(252) /  2/
      DATA JVEX(253) / 92/
      DATA NAM( 50),NS( 50) /'MEN',254/ !Mendocino Escarpment     
      DATA FN( 50) /'Mendocino Escarpment     '/
      DATA JVEX(254) / 89/
      DATA JVEX(255) / 93/
      DATA JVEX(256) / 92/
      DATA JVEX(257) / 91/
      DATA JVEX(258) / 90/
      DATA JVEX(259) / 88/
      DATA JVEX(260) / 85/
      DATA JVEX(261) / 86/
      DATA NAM( 51),NS( 51) /'EUR',262/ !Eureka                   
      DATA FN( 51) /'Eureka                   '/
      DATA JVEX(262) / 87/
      DATA JVEX(263) / 89/
      DATA JVEX(264) / 86/
      DATA NAM( 52),NS( 52) /'DEL',265/ !Del Norte                
      DATA FN( 52) /'Del Norte                '/
      DATA JVEX(265) / 82/
      DATA JVEX(266) / 87/
      DATA JVEX(267) / 86/
      DATA JVEX(268) / 85/
      DATA NAM( 53),NS( 53) /'SAC',269/ !Sacramento Valley        
      DATA FN( 53) /'Sacramento Valley        '/
      DATA JVEX(269) / 94/
      DATA JVEX(270) /100/
      DATA JVEX(271) /103/
      DATA JVEX(272) /110/
      DATA JVEX(273) / 14/
      DATA JVEX(274) /  5/
      DATA JVEX(275) / 93/
      DATA NAM( 54),NS( 54) /'JQN',276/ !San Joaquin Valley       
      DATA FN( 54) /'San Joaquin Valley       '/
      DATA JVEX(276) /110/
      DATA JVEX(277) /112/
      DATA JVEX(278) /115/
      DATA JVEX(279) / 78/
      DATA JVEX(280) / 69/
      DATA JVEX(281) / 62/
      DATA JVEX(282) / 49/
      DATA JVEX(283) / 25/
      DATA JVEX(284) / 14/
      DATA NAM( 55),NS( 55) /'KLA',285/ !Klamath Mountains        
      DATA FN( 55) /'Klamath Mountains        '/
      DATA JVEX(285) / 83/
      DATA JVEX(286) / 94/
      DATA JVEX(287) / 93/
      DATA JVEX(288) / 89/
      DATA JVEX(289) / 87/
      DATA JVEX(290) / 82/
      DATA NAM( 56),NS( 56) /'SHA',291/ !Shasta                   
      DATA FN( 56) /'Shasta                   '/
      DATA JVEX(291) / 84/
      DATA JVEX(292) / 99/
      DATA JVEX(293) / 98/
      DATA JVEX(294) / 96/
      DATA JVEX(295) / 95/
      DATA JVEX(296) / 97/
      DATA JVEX(297) / 94/
      DATA JVEX(298) / 83/
      DATA NAM( 57),NS( 57) /'LAS',299/ !Lassen                   
      DATA FN( 57) /'Lassen                   '/
      DATA JVEX(299) / 96/
      DATA JVEX(300) / 98/
      DATA JVEX(301) / 97/
      DATA JVEX(302) / 95/
      DATA NAM( 58),NS( 58) /'ALM',303/ !Lake Almanor             
      DATA FN( 58) /'Lake Almanor             '/
      DATA JVEX(303) / 99/
      DATA JVEX(304) /102/
      DATA JVEX(305) /101/
      DATA JVEX(306) /100/
      DATA JVEX(307) / 94/
      DATA JVEX(308) / 97/
      DATA JVEX(309) / 98/
      DATA NAM( 59),NS( 59) /'ORO',310/ !Oroville                 
      DATA FN( 59) /'Oroville                 '/
      DATA JVEX(310) /101/
      DATA JVEX(311) /104/
      DATA JVEX(312) /103/
      DATA JVEX(313) /100/
      DATA NAM( 60),NS( 60) /'AUB',314/ !Auburn                   
      DATA FN( 60) /'Auburn                   '/
      DATA JVEX(314) /104/
      DATA JVEX(315) /111/
      DATA JVEX(316) /110/
      DATA JVEX(317) /103/
      DATA NAM( 61),NS( 61) /'YOS',318/ !Yosemite                 
      DATA FN( 61) /'Yosemite                 '/
      DATA JVEX(318) /111/
      DATA JVEX(319) /113/
      DATA JVEX(320) /112/
      DATA JVEX(321) /110/
      DATA NAM( 62),NS( 62) /'WAK',322/ !Walker Lane              
      DATA FN( 62) /'Walker Lane              '/
      DATA JVEX(322) /102/
      DATA JVEX(323) /130/
      DATA JVEX(324) /114/
      DATA JVEX(325) /113/
      DATA JVEX(326) /111/
      DATA JVEX(327) /104/
      DATA JVEX(328) /101/
      DATA NAM( 63),NS( 63) /'MOB',329/ !Mono Basin %             
      DATA FN( 63) /'Mono Basin %             '/
      DATA JVEX(329) /114/
      DATA JVEX(330) /117/
      DATA JVEX(331) /122/
      DATA JVEX(332) /150/
      DATA JVEX(333) /149/
      DATA JVEX(334) /143/
      DATA JVEX(335) /140/
      DATA JVEX(336) /139/
      DATA JVEX(337) /127/
      DATA JVEX(338) /126/
      DATA JVEX(339) /125/
      DATA JVEX(340) /147/
      DATA JVEX(341) /146/
      DATA JVEX(342) /155/
      DATA JVEX(343) /180/
      DATA JVEX(344) /118/
      DATA JVEX(345) /113/
      DATA NAM( 64),NS( 64) /'BRC',346/ !Basin & Range Calif %    
      DATA FN( 64) /'Basin & Range Calif %    '/
      DATA JVEX(346) /164/
      DATA JVEX(347) /211/
      DATA JVEX(348) /242/
      DATA JVEX(349) /226/
      DATA JVEX(350) /233/
      DATA JVEX(351) /234/
      DATA JVEX(352) /195/
      DATA JVEX(353) /194/
      DATA JVEX(354) /221/
      DATA JVEX(355) /216/
      DATA JVEX(356) /201/
      DATA JVEX(357) /128/
      DATA JVEX(358) /171/
      DATA JVEX(359) /163/
      DATA JVEX(360) /150/
      DATA JVEX(361) /122/
      DATA JVEX(362) /117/
      DATA NAM( 65),NS( 65) /'KAI',363/ !Kaiser Peak              
      DATA FN( 65) /'Kaiser Peak              '/
      DATA JVEX(363) /113/
      DATA JVEX(364) /118/
      DATA JVEX(365) /180/
      DATA JVEX(366) /167/
      DATA JVEX(367) /168/
      DATA JVEX(368) /169/
      DATA JVEX(369) /170/
      DATA JVEX(370) /171/
      DATA JVEX(371) /128/
      DATA JVEX(372) /115/
      DATA JVEX(373) /112/
      DATA NAM( 66),NS( 66) /'LVC',374/ !Long Valley Caldera %    
      DATA FN( 66) /'Long Valley Caldera %    '/
      DATA JVEX(374) /125/
      DATA JVEX(375) /126/
      DATA JVEX(376) /127/
      DATA JVEX(377) /139/
      DATA JVEX(378) /140/
      DATA JVEX(379) /143/
      DATA JVEX(380) /149/
      DATA JVEX(381) /160/
      DATA JVEX(382) /159/
      DATA JVEX(383) /158/
      DATA JVEX(384) /154/
      DATA JVEX(385) /153/
      DATA JVEX(386) /156/
      DATA JVEX(387) /155/
      DATA JVEX(388) /146/
      DATA JVEX(389) /147/
      DATA NAM( 67),NS( 67) /'VOT',390/ !Volcanic Tableland %     
      DATA FN( 67) /'Volcanic Tableland %     '/
      DATA JVEX(390) /149/
      DATA JVEX(391) /150/
      DATA JVEX(392) /163/
      DATA JVEX(393) /171/
      DATA JVEX(394) /170/
      DATA JVEX(395) /169/
      DATA JVEX(396) /161/
      DATA JVEX(397) /160/
      DATA NAM( 68),NS( 68) /'RSM',398/ !Red Slate Mountain %     
      DATA FN( 68) /'Red Slate Mountain %     '/
      DATA JVEX(398) /180/
      DATA JVEX(399) /155/
      DATA JVEX(400) /156/
      DATA JVEX(401) /153/
      DATA JVEX(402) /154/
      DATA JVEX(403) /158/
      DATA JVEX(404) /159/
      DATA JVEX(405) /160/
      DATA JVEX(406) /161/
      DATA JVEX(407) /169/
      DATA JVEX(408) /168/
      DATA JVEX(409) /167/
      DATA NAM( 69),NS( 69) /'SCA',410/ !Southern Calif.          
      DATA FN( 69) /'Southern Calif.          '/
      DATA JVEX(410) /136/
      DATA JVEX(411) /137/
      DATA JVEX(412) /200/
      DATA JVEX(413) /199/
      DATA JVEX(414) /196/
      DATA JVEX(415) /195/
      DATA JVEX(416) /234/
      DATA JVEX(417) /233/
      DATA JVEX(418) /226/
      DATA JVEX(419) /242/
      DATA NAM( 70),NS( 70) /'PON',420/ !Pacific Ocean N          
      DATA FN( 70) /'Pacific Ocean N          '/
      DATA JVEX(420) /133/
      DATA JVEX(421) / 82/
      DATA JVEX(422) / 85/
      DATA JVEX(423) / 88/
      DATA JVEX(424) / 90/
      DATA JVEX(425) /105/
      DATA JVEX(426) /106/
      DATA JVEX(427) /  6/
      DATA JVEX(428) /119/
      DATA JVEX(429) /132/
      DATA NAM( 71),NS( 71) /'ORE',430/ !Oregon                   
      DATA FN( 71) /'Oregon                   '/
      DATA JVEX(430) /133/
      DATA JVEX(431) /134/
      DATA JVEX(432) /135/
      DATA JVEX(433) /131/
      DATA JVEX(434) / 84/
      DATA JVEX(435) / 83/
      DATA JVEX(436) / 82/
      DATA NAM( 72),NS( 72) /'MOD',437/ !Modoc Plateau            
      DATA FN( 72) /'Modoc Plateau            '/
      DATA JVEX(437) / 84/
      DATA JVEX(438) /131/
      DATA JVEX(439) /130/
      DATA JVEX(440) /102/
      DATA JVEX(441) / 99/
      DATA NAM( 73),NS( 73) /'NEV',442/ !Nevada                   
      DATA FN( 73) /'Nevada                   '/
      DATA JVEX(442) /131/
      DATA JVEX(443) /135/
      DATA JVEX(444) /136/
      DATA JVEX(445) /242/
      DATA JVEX(446) /211/
      DATA JVEX(447) /164/
      DATA JVEX(448) /117/
      DATA JVEX(449) /114/
      DATA JVEX(450) /130/
      DATA NAM( 74),NS( 74) /'MCA',451/ !Mono Caldera (MOB)       
      DATA FN( 74) /'Mono Caldera (MOB)       '/
      DATA JVEX(451) /118/
      DATA JVEX(452) /120/
      DATA JVEX(453) /126/
      DATA JVEX(454) /125/
      DATA JVEX(455) /147/
      DATA JVEX(456) /146/
      DATA JVEX(457) /155/
      DATA JVEX(458) /180/
      DATA NAM( 75),NS( 75) /'BAK',459/ !Bakersfield              
      DATA FN( 75) /'Bakersfield              '/
      DATA JVEX(459) /128/
      DATA JVEX(460) /198/
      DATA JVEX(461) / 81/
      DATA JVEX(462) / 77/
      DATA JVEX(463) / 78/
      DATA JVEX(464) /115/
      DATA NAM( 76),NS( 76) /'WWF',465/ !White Wolf Fault         
      DATA FN( 76) /'White Wolf Fault         '/
      DATA JVEX(465) /128/
      DATA JVEX(466) /201/
      DATA JVEX(467) /216/
      DATA JVEX(468) /221/
      DATA JVEX(469) /194/
      DATA JVEX(470) /197/
      DATA JVEX(471) /198/
      DATA NAM( 77),NS( 77) /'GLA',472/ !Glass Mtn. (MOB)         
      DATA FN( 77) /'Glass Mtn. (MOB)         '/
      DATA JVEX(472) /121/
      DATA JVEX(473) /122/
      DATA JVEX(474) /150/
      DATA JVEX(475) /149/
      DATA JVEX(476) /143/
      DATA JVEX(477) /140/
      DATA JVEX(478) /139/
      DATA JVEX(479) /127/
      DATA JVEX(480) /126/
      DATA JVEX(481) /120/
      DATA NAM( 78),NS( 78) /'MOL',482/ !Mono Lake (MOB)          
      DATA FN( 78) /'Mono Lake (MOB)          '/
      DATA JVEX(482) /114/
      DATA JVEX(483) /117/
      DATA JVEX(484) /122/
      DATA JVEX(485) /121/
      DATA JVEX(486) /120/
      DATA JVEX(487) /118/
      DATA JVEX(488) /113/
      DATA NAM( 79),NS( 79) /'CHV',489/ !Chalfant Valley (BRC)    
      DATA FN( 79) /'Chalfant Valley (BRC)    '/
      DATA JVEX(489) /122/
      DATA JVEX(490) /117/
      DATA JVEX(491) /123/
      DATA JVEX(492) /172/
      DATA JVEX(493) /171/
      DATA JVEX(494) /163/
      DATA JVEX(495) /150/
      DATA NAM( 80),NS( 80) /'WHI',496/ !White Mountains (BRC)    
      DATA FN( 80) /'White Mountains (BRC)    '/
      DATA JVEX(496) /117/
      DATA JVEX(497) /164/
      DATA JVEX(498) /176/
      DATA JVEX(499) /172/
      DATA JVEX(500) /123/
      DATA NAM( 81),NS( 81) /'COS',501/ !Coso Range (BRC)         
      DATA FN( 81) /'Coso Range (BRC)         '/
      DATA JVEX(501) /202/
      DATA JVEX(502) /207/
      DATA JVEX(503) /222/
      DATA JVEX(504) /221/
      DATA JVEX(505) /216/
      DATA NAM( 82),NS( 82) /'IWV',506/ !Indian Wells Val. (BRC)  
      DATA FN( 82) /'Indian Wells Val. (BRC)  '/
      DATA JVEX(506) /221/
      DATA JVEX(507) /222/
      DATA JVEX(508) /195/
      DATA JVEX(509) /194/
      DATA NAM( 83),NS( 83) /'GAR',510/ !Garlock Fault            
      DATA FN( 83) /'Garlock Fault            '/
      DATA JVEX(510) /194/
      DATA JVEX(511) /195/
      DATA JVEX(512) /196/
      DATA JVEX(513) /197/
      DATA NAM( 84),NS( 84) /'OWV',514/ !Owens Valley (BRC)       
      DATA FN( 84) /'Owens Valley (BRC)       '/
      DATA JVEX(514) /171/
      DATA JVEX(515) /172/
      DATA JVEX(516) /176/
      DATA JVEX(517) /193/
      DATA JVEX(518) /202/
      DATA JVEX(519) /216/
      DATA JVEX(520) /201/
      DATA JVEX(521) /128/
      DATA NAM( 85),NS( 85) /'DEV',522/ !Death Valley (BRC)       
      DATA FN( 85) /'Death Valley (BRC)       '/
      DATA JVEX(522) /164/
      DATA JVEX(523) /211/
      DATA JVEX(524) /242/
      DATA JVEX(525) /226/
      DATA JVEX(526) /233/
      DATA JVEX(527) /234/
      DATA JVEX(528) /195/
      DATA JVEX(529) /222/
      DATA JVEX(530) /207/
      DATA JVEX(531) /202/
      DATA JVEX(532) /193/
      DATA JVEX(533) /176/
      DATA NAM( 86),NS( 86) /'INC',534/ !Inyo Craters (LVC)       
      DATA FN( 86) /'Inyo Craters (LVC)       '/
      DATA JVEX(534) /125/
      DATA JVEX(535) /126/
      DATA JVEX(536) /127/
      DATA JVEX(537) /148/
      DATA JVEX(538) /147/
      DATA NAM( 87),NS( 87) /'WMO',539/ !West Moat (LVC)          
      DATA FN( 87) /'West Moat (LVC)          '/
      DATA JVEX(539) /127/
      DATA JVEX(540) /141/
      DATA JVEX(541) /145/
      DATA JVEX(542) /148/
      DATA NAM( 88),NS( 88) /'NMO',543/ !North Moat (LVC)         
      DATA FN( 88) /'North Moat (LVC)         '/
      DATA JVEX(543) /127/
      DATA JVEX(544) /139/
      DATA JVEX(545) /140/
      DATA JVEX(546) /144/
      DATA JVEX(547) /142/
      DATA JVEX(548) /141/
      DATA NAM( 89),NS( 89) /'EMO',549/ !East Moat (LVC)          
      DATA FN( 89) /'East Moat (LVC)          '/
      DATA JVEX(549) /140/
      DATA JVEX(550) /143/
      DATA JVEX(551) /149/
      DATA JVEX(552) /160/
      DATA JVEX(553) /144/
      DATA NAM( 90),NS( 90) /'SMO',554/ !South Moat (LVC)         
      DATA FN( 90) /'South Moat (LVC)         '/
      DATA JVEX(554) /148/
      DATA JVEX(555) /145/
      DATA JVEX(556) /151/
      DATA JVEX(557) /152/
      DATA JVEX(558) /159/
      DATA JVEX(559) /158/
      DATA JVEX(560) /154/
      DATA JVEX(561) /153/
      DATA NAM( 91),NS( 91) /'DOM',562/ !Resurgent Dome (LVC)     
      DATA FN( 91) /'Resurgent Dome (LVC)     '/
      DATA JVEX(562) /141/
      DATA JVEX(563) /142/
      DATA JVEX(564) /144/
      DATA JVEX(565) /152/
      DATA JVEX(566) /151/
      DATA JVEX(567) /145/
      DATA NAM( 92),NS( 92) /'MAM',568/ !Mammoth Mtn. (LVC)       
      DATA FN( 92) /'Mammoth Mtn. (LVC)       '/
      DATA JVEX(568) /146/
      DATA JVEX(569) /147/
      DATA JVEX(570) /148/
      DATA JVEX(571) /153/
      DATA JVEX(572) /156/
      DATA JVEX(573) /155/
      DATA NAM( 93),NS( 93) /'HCF',574/ !Hilton Crk. Flt. (LVC)   
      DATA FN( 93) /'Hilton Crk. Flt. (LVC)   '/
      DATA JVEX(574) /152/
      DATA JVEX(575) /144/
      DATA JVEX(576) /160/
      DATA JVEX(577) /159/
      DATA NAM( 94),NS( 94) /'SBA',578/ !Santa Barbara            
      DATA FN( 94) /'Santa Barbara            '/
      DATA JVEX(578) / 81/
      DATA JVEX(579) /198/
      DATA JVEX(580) /197/
      DATA JVEX(581) /196/
      DATA JVEX(582) /199/
      DATA JVEX(583) /200/
      DATA JVEX(584) / 79/
      DATA JVEX(585) / 80/
      DATA NAM( 95),NS( 95) /'CAS',586/ !Casa Diablo Mtn. (VOT)   
      DATA FN( 95) /'Casa Diablo Mtn. (VOT)   '/
      DATA JVEX(586) /149/
      DATA JVEX(587) /150/
      DATA JVEX(588) /163/
      DATA JVEX(589) /162/
      DATA JVEX(590) /161/
      DATA JVEX(591) /160/
      DATA NAM( 96),NS( 96) /'RVL',592/ !Round Valley (VOT)       
      DATA FN( 96) /'Round Valley (VOT)       '/
      DATA JVEX(592) /161/
      DATA JVEX(593) /162/
      DATA JVEX(594) /170/
      DATA JVEX(595) /169/
      DATA NAM( 97),NS( 97) /'CHA',596/ !Chalk Bluffs (VOT)       
      DATA FN( 97) /'Chalk Bluffs (VOT)       '/
      DATA JVEX(596) /162/
      DATA JVEX(597) /163/
      DATA JVEX(598) /171/
      DATA JVEX(599) /170/
      DATA NAM( 98),NS( 98) /'MOR',600/ !Mt. Morrison (RSM)       
      DATA FN( 98) /'Mt. Morrison (RSM)       '/
      DATA JVEX(600) /157/
      DATA JVEX(601) /158/
      DATA JVEX(602) /159/
      DATA JVEX(603) /160/
      DATA JVEX(604) /166/
      DATA JVEX(605) /165/
      DATA NAM( 99),NS( 99) /'SHE',606/ !Sherwin Lakes (RSM)      
      DATA FN( 99) /'Sherwin Lakes (RSM)      '/
      DATA JVEX(606) /153/
      DATA JVEX(607) /154/
      DATA JVEX(608) /158/
      DATA JVEX(609) /157/
      DATA JVEX(610) /156/
      DATA NAM(100),NS(100) /'SIL',611/ !Silver Peak (RSM)        
      DATA FN(100) /'Silver Peak (RSM)        '/
      DATA JVEX(611) /180/
      DATA JVEX(612) /155/
      DATA JVEX(613) /156/
      DATA JVEX(614) /157/
      DATA JVEX(615) /165/
      DATA JVEX(616) /166/
      DATA JVEX(617) /168/
      DATA JVEX(618) /167/
      DATA NAM(101),NS(101) /'WCN',619/ !Wheeler Crest No. (RSM)  
      DATA FN(101) /'Wheeler Crest No. (RSM)  '/
      DATA JVEX(619) /160/
      DATA JVEX(620) /161/
      DATA JVEX(621) /166/
      DATA NAM(102),NS(102) /'WCS',622/ !Wheeler Crest So. (RSM)  
      DATA FN(102) /'Wheeler Crest So. (RSM)  '/
      DATA JVEX(622) /166/
      DATA JVEX(623) /161/
      DATA JVEX(624) /169/
      DATA JVEX(625) /168/
      DATA NAM(103),NS(103) /'POS',626/ !Pacific Ocean S          
      DATA FN(103) /'Pacific Ocean S          '/
      DATA JVEX(626) /  6/
      DATA JVEX(627) / 16/
      DATA JVEX(628) / 15/
      DATA JVEX(629) / 26/
      DATA JVEX(630) / 40/
      DATA JVEX(631) / 63/
      DATA JVEX(632) / 79/
      DATA JVEX(633) /200/
      DATA JVEX(634) /137/
      DATA JVEX(635) /138/
      DATA JVEX(636) /119/
