C--THESE ARE THE VERTEX COORDS IN DECIMAL DEGREES
      DATA PY(  1),PX(  1) /19.5000,-155.3333/
      DATA PY(  2),PX(  2) /19.4917,-155.2867/
      DATA PY(  3),PX(  3) /19.4792,-155.2100/
      DATA PY(  4),PX(  4) /19.4192,-155.2392/
      DATA PY(  5),PX(  5) /19.3900,-155.2758/
      DATA PY(  6),PX(  6) /19.4117,-155.2842/
      DATA PY(  7),PX(  7) /19.4167,-155.3075/
      DATA PY(  8),PX(  8) /19.3783,-155.2842/
      DATA PY(  9),PX(  9) /19.3850,-155.3167/
      DATA PY( 10),PX( 10) /19.3600,-155.3550/
      DATA PY( 11),PX( 11) /19.4142,-155.2100/
      DATA PY( 12),PX( 12) /19.3750,-155.2592/
      DATA PY( 13),PX( 13) /19.3858,-155.2250/
      DATA PY( 14),PX( 14) /19.3592,-155.2392/
      DATA PY( 15),PX( 15) /19.3475,-155.2450/
      DATA PY( 16),PX( 16) /19.3375,-155.3117/
      DATA PY( 17),PX( 17) /19.3050,-155.3700/
      DATA PY( 18),PX( 18) /19.3000,-155.3783/
      DATA PY( 19),PX( 19) /19.2642,-155.3842/
      DATA PY( 20),PX( 20) /19.2567,-155.4108/
      DATA PY( 21),PX( 21) /19.3150,-155.4267/
      DATA PY( 22),PX( 22) /19.3367,-155.3917/
      DATA PY( 23),PX( 23) /19.2250,-155.2742/
      DATA PY( 24),PX( 24) /19.1833,-155.3900/
      DATA PY( 25),PX( 25) /19.1067,-155.5350/
      DATA PY( 26),PX( 26) /19.1067,-155.7167/
      DATA PY( 27),PX( 27) /19.2333,-155.7167/
      DATA PY( 28),PX( 28) /19.3700,-155.6058/
      DATA PY( 29),PX( 29) /19.4817,-155.5150/
      DATA PY( 30),PX( 30) /19.5000,-155.5000/
      DATA PY( 31),PX( 31) /19.5467,-155.5683/
      DATA PY( 32),PX( 32) /19.4267,-155.6775/
      DATA PY( 33),PX( 33) /19.6500,-155.3333/
      DATA PY( 34),PX( 34) /19.6500,-155.2100/
      DATA PY( 35),PX( 35) /19.6500,-154.8333/
      DATA PY( 36),PX( 36) /19.4008,-155.1392/
      DATA PY( 37),PX( 37) /19.4717,-154.9658/
      DATA PY( 38),PX( 38) /19.4233,-154.9475/
      DATA PY( 39),PX( 39) /19.3617,-155.1267/
      DATA PY( 40),PX( 40) /19.2758,-155.1067/
      DATA PY( 41),PX( 41) /19.3767,-154.8975/
      DATA PY( 42),PX( 42) /19.3167,-154.9683/
      DATA PY( 43),PX( 43) /19.5000,-154.9533/
      DATA PY( 44),PX( 44) /19.5450,-154.8333/
      DATA PY( 45),PX( 45) /19.4500,-154.7583/
      DATA PY( 46),PX( 46) /19.2558,-155.1667/
      DATA PY( 47),PX( 47) /19.1500,-155.2500/
      DATA PY( 48),PX( 48) /19.0442,-155.1508/
      DATA PY( 49),PX( 49) /19.0442,-155.3517/
      DATA PY( 50),PX( 50) /18.9558,-155.4283/
      DATA PY( 51),PX( 51) /18.6667,-155.4283/
      DATA PY( 52),PX( 52) /18.6667,-155.1508/
      DATA PY( 53),PX( 53) /19.4167,-154.6833/
      DATA PY( 54),PX( 54) /19.3633,-155.1700/
      DATA PY( 55),PX( 55) /19.2633,-155.1467/
      DATA PY( 56),PX( 56) /19.2417,-155.2250/
      DATA PY( 57),PX( 57) /19.3283,-155.2533/
      DATA PY( 58),PX( 58) /19.4050,-155.0442/
      DATA PY( 59),PX( 59) /19.4392,-154.9533/
      DATA PY( 60),PX( 60) /19.2842,-155.0767/
      DATA PY( 61),PX( 61) /19.2583,-155.8000/
      DATA PY( 62),PX( 62) /19.6500,-155.7500/
      DATA PY( 63),PX( 63) /19.1108,-155.3700/
      DATA PY( 64),PX( 64) /18.8333,-155.7500/
      DATA PY( 65),PX( 65) /19.4500,-155.3558/
      DATA PY( 66),PX( 66) /19.4225,-155.1667/
      DATA PY( 67),PX( 67) /19.6500,-155.1667/
      DATA PY( 68),PX( 68) /19.2283,-154.8333/
      DATA PY( 69),PX( 69) /19.3817,-155.1000/
      DATA PY( 70),PX( 70) /19.2500,-155.9000/
      DATA PY( 71),PX( 71) /18.8667,-156.2500/
      DATA PY( 72),PX( 72) /19.9833,-156.6667/
      DATA PY( 73),PX( 73) /19.7417,-156.3583/
      DATA PY( 74),PX( 74) /19.5333,-156.0833/
      DATA PY( 75),PX( 75) /20.2000,-156.5000/
      DATA PY( 76),PX( 76) /20.0667,-156.1333/
      DATA PY( 77),PX( 77) /19.8750,-155.7333/
      DATA PY( 78),PX( 78) /20.4167,-155.9667/
      DATA PY( 79),PX( 79) /20.3000,-155.5000/
      DATA PY( 80),PX( 80) /19.9833,-155.0167/
      DATA PY( 81),PX( 81) /19.7333,-154.7500/
      DATA PY( 82),PX( 82) /19.5917,-154.6167/

C--FOR EACH REGION, DEFINE ITS NAME, POINTER TO FIRST
C--VERTEX, AND ORDERED LIST OF VERTICIES
      DATA NAM(  1),NS(  1) /'SNC',  1/ !Shallow north caldera    
      DATA FN(  1) /'Shallow north caldera    '/
      DATA JVEX(  1) /  2/
      DATA JVEX(  2) /  3/
      DATA JVEX(  3) /  4/
      DATA JVEX(  4) /  6/
      DATA JVEX(  5) /  7/
      DATA NAM(  2),NS(  2) /'SEC',  6/ !Shallow east caldera     
      DATA FN(  2) /'Shallow east caldera     '/
      DATA JVEX(  6) /  4/
      DATA JVEX(  7) /  5/
      DATA JVEX(  8) /  6/
      DATA NAM(  3),NS(  3) /'SSC',  9/ !Shallow south caldera    
      DATA FN(  3) /'Shallow south caldera    '/
      DATA JVEX(  9) /  6/
      DATA JVEX( 10) /  5/
      DATA JVEX( 11) /  8/
      DATA JVEX( 12) /  9/
      DATA JVEX( 13) /  7/
      DATA NAM(  4),NS(  4) /'KOA', 14/ !Koae Fault               
      DATA FN(  4) /'Koae Fault               '/
      DATA JVEX( 14) /  5/
      DATA JVEX( 15) / 15/
      DATA JVEX( 16) / 16/
      DATA JVEX( 17) /  8/
      DATA NAM(  5),NS(  5) /'UER', 18/ !Uppermost East Rift      
      DATA FN(  5) /'Uppermost East Rift      '/
      DATA JVEX( 18) /  4/
      DATA JVEX( 19) / 13/
      DATA JVEX( 20) / 15/
      DATA JVEX( 21) /  5/
      DATA NAM(  6),NS(  6) /'ERZ', 22/ !East Rift                
      DATA FN(  6) /'East Rift                '/
      DATA JVEX( 22) / 13/
      DATA JVEX( 23) / 36/
      DATA JVEX( 24) / 39/
      DATA JVEX( 25) / 15/
      DATA NAM(  7),NS(  7) /'MER', 26/ !Middle East Rift         
      DATA FN(  7) /'Middle East Rift         '/
      DATA JVEX( 26) / 36/
      DATA JVEX( 27) / 37/
      DATA JVEX( 28) / 59/
      DATA JVEX( 29) / 38/
      DATA JVEX( 30) / 39/
      DATA NAM(  8),NS(  8) /'SLE', 31/ !Shallow Lower East Rift  
      DATA FN(  8) /'Shallow Lower East Rift  '/
      DATA JVEX( 31) / 37/
      DATA JVEX( 32) / 43/
      DATA JVEX( 33) / 44/
      DATA JVEX( 34) / 45/
      DATA JVEX( 35) / 41/
      DATA JVEX( 36) / 38/
      DATA JVEX( 37) / 59/
      DATA NAM(  9),NS(  9) /'SWR', 38/ !Southwest Rift           
      DATA FN(  9) /'Southwest Rift           '/
      DATA JVEX( 38) /  9/
      DATA JVEX( 39) /  8/
      DATA JVEX( 40) / 16/
      DATA JVEX( 41) / 17/
      DATA JVEX( 42) / 22/
      DATA JVEX( 43) / 10/
      DATA NAM( 10),NS( 10) /'MSW', 44/ !Middle SW Rift           
      DATA FN( 10) /'Middle SW Rift           '/
      DATA JVEX( 44) / 17/
      DATA JVEX( 45) / 18/
      DATA JVEX( 46) / 19/
      DATA JVEX( 47) / 20/
      DATA JVEX( 48) / 21/
      DATA JVEX( 49) / 22/
      DATA NAM( 11),NS( 11) /'SSW', 50/ !Shallow south flank west 
      DATA FN( 11) /'Shallow south flank west '/
      DATA JVEX( 50) / 16/
      DATA JVEX( 51) / 23/
      DATA JVEX( 52) / 47/
      DATA JVEX( 53) / 63/
      DATA JVEX( 54) / 24/
      DATA JVEX( 55) / 20/
      DATA JVEX( 56) / 19/
      DATA JVEX( 57) / 18/
      DATA JVEX( 58) / 17/
      DATA NAM( 12),NS( 12) /'SSF', 59/ !Shallow south flank      
      DATA FN( 12) /'Shallow south flank      '/
      DATA JVEX( 59) / 15/
      DATA JVEX( 60) / 39/
      DATA JVEX( 61) / 40/
      DATA JVEX( 62) / 55/
      DATA JVEX( 63) / 46/
      DATA JVEX( 64) / 56/
      DATA JVEX( 65) / 23/
      DATA JVEX( 66) / 16/
      DATA NAM( 13),NS( 13) /'SSE', 67/ !Shallow south flank east 
      DATA FN( 13) /'Shallow south flank east '/
      DATA JVEX( 67) / 38/
      DATA JVEX( 68) / 41/
      DATA JVEX( 69) / 42/
      DATA JVEX( 70) / 60/
      DATA JVEX( 71) / 40/
      DATA JVEX( 72) / 39/
      DATA NAM( 14),NS( 14) /'SWC', 73/ !Shallow west caldera     
      DATA FN( 14) /'Shallow west caldera     '/
      DATA JVEX( 73) /  1/
      DATA JVEX( 74) /  2/
      DATA JVEX( 75) /  7/
      DATA JVEX( 76) /  9/
      DATA JVEX( 77) / 10/
      DATA NAM( 15),NS( 15) /'KAO', 78/ !Kaoiki seismic zone 0-14 
      DATA FN( 15) /'Kaoiki seismic zone 0-14 '/
      DATA JVEX( 78) /  1/
      DATA JVEX( 79) / 10/
      DATA JVEX( 80) / 22/
      DATA JVEX( 81) / 21/
      DATA JVEX( 82) / 28/
      DATA JVEX( 83) / 29/
      DATA JVEX( 84) / 30/
      DATA NAM( 16),NS( 16) /'HLE', 85/ !Hilea seismic zone 0-14  
      DATA FN( 16) /'Hilea seismic zone 0-14  '/
      DATA JVEX( 85) / 21/
      DATA JVEX( 86) / 20/
      DATA JVEX( 87) / 24/
      DATA JVEX( 88) / 25/
      DATA JVEX( 89) / 26/
      DATA JVEX( 90) / 27/
      DATA JVEX( 91) / 28/
      DATA NAM( 17),NS( 17) /'MOK', 92/ !Mokuaweoweo Caldera 0-14 
      DATA FN( 17) /'Mokuaweoweo Caldera 0-14 '/
      DATA JVEX( 92) / 29/
      DATA JVEX( 93) / 28/
      DATA JVEX( 94) / 32/
      DATA JVEX( 95) / 31/
      DATA NAM( 18),NS( 18) /'MWF', 96/ !Mauna Loa west flank 0-14
      DATA FN( 18) /'Mauna Loa west flank 0-14'/
      DATA JVEX( 96) / 31/
      DATA JVEX( 97) / 32/
      DATA JVEX( 98) / 62/
      DATA JVEX( 99) / 33/
      DATA NAM( 19),NS( 19) /'MNE',100/ !Mauna Loa NE rift 0-14   
      DATA FN( 19) /'Mauna Loa NE rift 0-14   '/
      DATA JVEX(100) /  1/
      DATA JVEX(101) / 30/
      DATA JVEX(102) / 29/
      DATA JVEX(103) / 31/
      DATA JVEX(104) / 33/
      DATA JVEX(105) / 34/
      DATA JVEX(106) /  3/
      DATA JVEX(107) /  2/
      DATA NAM( 20),NS( 20) /'GLE',108/ !Glenwood 0-14 km         
      DATA FN( 20) /'Glenwood 0-14 km         '/
      DATA JVEX(108) /  3/
      DATA JVEX(109) / 34/
      DATA JVEX(110) / 35/
      DATA JVEX(111) / 44/
      DATA JVEX(112) / 43/
      DATA JVEX(113) / 37/
      DATA JVEX(114) / 36/
      DATA JVEX(115) / 11/
      DATA NAM( 21),NS( 21) /'OSW',116/ !Offshore SW Rift 0-14    
      DATA FN( 21) /'Offshore SW Rift 0-14    '/
      DATA JVEX(116) / 24/
      DATA JVEX(117) / 63/
      DATA JVEX(118) / 47/
      DATA JVEX(119) / 48/
      DATA JVEX(120) / 49/
      DATA JVEX(121) / 50/
      DATA JVEX(122) / 51/
      DATA JVEX(123) / 64/
      DATA JVEX(124) / 26/
      DATA JVEX(125) / 25/
      DATA NAM( 22),NS( 22) /'OER',126/ !Offshore East Rift 0-14  
      DATA FN( 22) /'Offshore East Rift 0-14  '/
      DATA JVEX(126) / 23/
      DATA JVEX(127) / 56/
      DATA JVEX(128) / 46/
      DATA JVEX(129) / 55/
      DATA JVEX(130) / 40/
      DATA JVEX(131) / 60/
      DATA JVEX(132) / 42/
      DATA JVEX(133) / 41/
      DATA JVEX(134) / 45/
      DATA JVEX(135) / 53/
      DATA JVEX(136) / 48/
      DATA JVEX(137) / 47/
      DATA NAM( 23),NS( 23) /'STS',138/ !Shallow Thurston shield  
      DATA FN( 23) /'Shallow Thurston shield  '/
      DATA JVEX(138) /  3/
      DATA JVEX(139) / 11/
      DATA JVEX(140) / 36/
      DATA JVEX(141) / 13/
      DATA JVEX(142) /  4/
      DATA NAM( 24),NS( 24) /'LOI',143/ !Loihi 0-20 km            
      DATA FN( 24) /'Loihi 0-20 km            '/
      DATA JVEX(143) / 48/
      DATA JVEX(144) / 52/
      DATA JVEX(145) / 51/
      DATA JVEX(146) / 50/
      DATA JVEX(147) / 49/
      DATA NAM( 25),NS( 25) /'SF0',148/ !South Flank 0 (4.5-14 km)
      DATA FN( 25) /'South Flank 0 (4.5-14 km)'/
      DATA JVEX(148) / 16/
      DATA JVEX(149) / 23/
      DATA JVEX(150) / 47/
      DATA JVEX(151) / 63/
      DATA JVEX(152) / 24/
      DATA JVEX(153) / 20/
      DATA JVEX(154) / 19/
      DATA JVEX(155) / 18/
      DATA JVEX(156) / 17/
      DATA NAM( 26),NS( 26) /'SF1',157/ !South Flank 1 (4.5-14 km)
      DATA FN( 26) /'South Flank 1 (4.5-14 km)'/
      DATA JVEX(157) /  8/
      DATA JVEX(158) / 12/
      DATA JVEX(159) / 14/
      DATA JVEX(160) / 57/
      DATA JVEX(161) / 56/
      DATA JVEX(162) / 23/
      DATA JVEX(163) / 16/
      DATA NAM( 27),NS( 27) /'SF2',164/ !South Flank 2 (4.5-14 km)
      DATA FN( 27) /'South Flank 2 (4.5-14 km)'/
      DATA JVEX(164) / 14/
      DATA JVEX(165) / 54/
      DATA JVEX(166) / 55/
      DATA JVEX(167) / 46/
      DATA JVEX(168) / 56/
      DATA JVEX(169) / 57/
      DATA NAM( 28),NS( 28) /'SF3',170/ !South Flank 3 (4.5-14 km)
      DATA FN( 28) /'South Flank 3 (4.5-14 km)'/
      DATA JVEX(170) / 54/
      DATA JVEX(171) / 69/
      DATA JVEX(172) / 60/
      DATA JVEX(173) / 40/
      DATA JVEX(174) / 55/
      DATA NAM( 29),NS( 29) /'SF4',175/ !South Flank 4 (4.5-14 km)
      DATA FN( 29) /'South Flank 4 (4.5-14 km)'/
      DATA JVEX(175) / 69/
      DATA JVEX(176) / 58/
      DATA JVEX(177) / 42/
      DATA JVEX(178) / 60/
      DATA NAM( 30),NS( 30) /'SF5',179/ !South Flank 5 (4.5-14 km)
      DATA FN( 30) /'South Flank 5 (4.5-14 km)'/
      DATA JVEX(179) / 58/
      DATA JVEX(180) / 59/
      DATA JVEX(181) / 38/
      DATA JVEX(182) / 41/
      DATA JVEX(183) / 42/
      DATA NAM( 31),NS( 31) /'INT',184/ !Intermed. depth caldera  
      DATA FN( 31) /'Intermed. depth caldera  '/
      DATA JVEX(184) /  2/
      DATA JVEX(185) /  3/
      DATA JVEX(186) / 11/
      DATA JVEX(187) / 12/
      DATA JVEX(188) /  8/
      DATA JVEX(189) /  9/
      DATA JVEX(190) /  7/
      DATA NAM( 32),NS( 32) /'IWC',191/ !Intermed. west caldera   
      DATA FN( 32) /'Intermed. west caldera   '/
      DATA JVEX(191) /  1/
      DATA JVEX(192) /  2/
      DATA JVEX(193) /  7/
      DATA JVEX(194) /  9/
      DATA JVEX(195) / 10/
      DATA NAM( 33),NS( 33) /'BSW',196/ !Bottom depth SW Rift 5-14
      DATA FN( 33) /'Bottom depth SW Rift 5-14'/
      DATA JVEX(196) /  8/
      DATA JVEX(197) / 16/
      DATA JVEX(198) / 17/
      DATA JVEX(199) / 18/
      DATA JVEX(200) / 19/
      DATA JVEX(201) / 20/
      DATA JVEX(202) / 21/
      DATA JVEX(203) / 22/
      DATA JVEX(204) / 10/
      DATA JVEX(205) /  9/
      DATA NAM( 34),NS( 34) /'BER',206/ !Bottom depth E. Rift 5-14
      DATA FN( 34) /'Bottom depth E. Rift 5-14'/
      DATA JVEX(206) / 11/
      DATA JVEX(207) / 36/
      DATA JVEX(208) / 37/
      DATA JVEX(209) / 59/
      DATA JVEX(210) / 58/
      DATA JVEX(211) / 69/
      DATA JVEX(212) / 54/
      DATA JVEX(213) / 14/
      DATA JVEX(214) / 12/
      DATA NAM( 35),NS( 35) /'LER',215/ !Lower East Rift 4.5-14 km
      DATA FN( 35) /'Lower East Rift 4.5-14 km'/
      DATA JVEX(215) / 37/
      DATA JVEX(216) / 43/
      DATA JVEX(217) / 44/
      DATA JVEX(218) / 45/
      DATA JVEX(219) / 41/
      DATA JVEX(220) / 38/
      DATA JVEX(221) / 59/
      DATA NAM( 36),NS( 36) /'DEP',222/ !Deep Kilauea conduit     
      DATA FN( 36) /'Deep Kilauea conduit     '/
      DATA JVEX(222) / 65/
      DATA JVEX(223) / 66/
      DATA JVEX(224) / 46/
      DATA JVEX(225) / 21/
      DATA NAM( 37),NS( 37) /'DEN',226/ !Deep Kilauea north 20-70 
      DATA FN( 37) /'Deep Kilauea north 20-70 '/
      DATA JVEX(226) /  1/
      DATA JVEX(227) / 33/
      DATA JVEX(228) / 67/
      DATA JVEX(229) / 66/
      DATA JVEX(230) / 65/
      DATA NAM( 38),NS( 38) /'DSF',231/ !Deep south flank 20-70 km
      DATA FN( 38) /'Deep south flank 20-70 km'/
      DATA JVEX(231) / 21/
      DATA JVEX(232) / 46/
      DATA JVEX(233) / 48/
      DATA JVEX(234) / 49/
      DATA NAM( 39),NS( 39) /'DLS',235/ !Deep lower SW Rift 20-70 
      DATA FN( 39) /'Deep lower SW Rift 20-70 '/
      DATA JVEX(235) / 21/
      DATA JVEX(236) / 49/
      DATA JVEX(237) / 50/
      DATA JVEX(238) / 51/
      DATA JVEX(239) / 64/
      DATA JVEX(240) / 26/
      DATA JVEX(241) / 27/
      DATA NAM( 40),NS( 40) /'DML',242/ !Deep Mauna Loa 20-70 km  
      DATA FN( 40) /'Deep Mauna Loa 20-70 km  '/
      DATA JVEX(242) /  1/
      DATA JVEX(243) / 65/
      DATA JVEX(244) / 21/
      DATA JVEX(245) / 27/
      DATA JVEX(246) / 61/
      DATA JVEX(247) / 32/
      DATA JVEX(248) / 62/
      DATA JVEX(249) / 33/
      DATA NAM( 41),NS( 41) /'DER',250/ !Deep Kilauea East Rift   
      DATA FN( 41) /'Deep Kilauea East Rift   '/
      DATA JVEX(250) / 46/
      DATA JVEX(251) / 66/
      DATA JVEX(252) / 53/
      DATA JVEX(253) / 68/
      DATA JVEX(254) / 48/
      DATA NAM( 42),NS( 42) /'DLO',255/ !Deep Loihi 20-70 km      
      DATA FN( 42) /'Deep Loihi 20-70 km      '/
      DATA JVEX(255) / 48/
      DATA JVEX(256) / 52/
      DATA JVEX(257) / 51/
      DATA JVEX(258) / 50/
      DATA JVEX(259) / 49/
      DATA NAM( 43),NS( 43) /'DHL',260/ !Deep Hilo 20-70 km       
      DATA FN( 43) /'Deep Hilo 20-70 km       '/
      DATA JVEX(260) / 66/
      DATA JVEX(261) / 67/
      DATA JVEX(262) / 80/
      DATA JVEX(263) / 81/
      DATA JVEX(264) / 82/
      DATA JVEX(265) / 53/
      DATA NAM( 44),NS( 44) /'CON',266/ !Kilauea conduit 14-20 km 
      DATA FN( 44) /'Kilauea conduit 14-20 km '/
      DATA JVEX(266) /  1/
      DATA JVEX(267) /  3/
      DATA JVEX(268) / 11/
      DATA JVEX(269) / 12/
      DATA JVEX(270) / 10/
      DATA NAM( 45),NS( 45) /'IHL',271/ !Intermed. Hilea 14-20 km 
      DATA FN( 45) /'Intermed. Hilea 14-20 km '/
      DATA JVEX(271) / 21/
      DATA JVEX(272) / 49/
      DATA JVEX(273) / 50/
      DATA JVEX(274) / 51/
      DATA JVEX(275) / 64/
      DATA JVEX(276) / 26/
      DATA JVEX(277) / 27/
      DATA JVEX(278) / 28/
      DATA NAM( 46),NS( 46) /'IKA',279/ !Intermed. Kaoiki 14-20 km
      DATA FN( 46) /'Intermed. Kaoiki 14-20 km'/
      DATA JVEX(279) /  1/
      DATA JVEX(280) / 10/
      DATA JVEX(281) / 21/
      DATA JVEX(282) / 28/
      DATA JVEX(283) / 30/
      DATA NAM( 47),NS( 47) /'IML',284/ !Intermed. Mauna Loa 14-20
      DATA FN( 47) /'Intermed. Mauna Loa 14-20'/
      DATA JVEX(284) / 28/
      DATA JVEX(285) / 27/
      DATA JVEX(286) / 61/
      DATA JVEX(287) / 32/
      DATA JVEX(288) / 62/
      DATA JVEX(289) / 33/
      DATA JVEX(290) /  1/
      DATA JVEX(291) / 30/
      DATA NAM( 48),NS( 48) /'IHI',292/ !Intermed. Hilo 14-20 km  
      DATA FN( 48) /'Intermed. Hilo 14-20 km  '/
      DATA JVEX(292) /  1/
      DATA JVEX(293) / 33/
      DATA JVEX(294) / 67/
      DATA JVEX(295) / 35/
      DATA JVEX(296) / 81/
      DATA JVEX(297) / 82/
      DATA JVEX(298) / 53/
      DATA JVEX(299) / 11/
      DATA JVEX(300) /  3/
      DATA NAM( 49),NS( 49) /'IER',301/ !Intermed. East Rift 14-20
      DATA FN( 49) /'Intermed. East Rift 14-20'/
      DATA JVEX(301) / 11/
      DATA JVEX(302) / 53/
      DATA JVEX(303) / 68/
      DATA JVEX(304) / 48/
      DATA JVEX(305) / 46/
      DATA JVEX(306) / 12/
      DATA NAM( 50),NS( 50) /'ISF',307/ !Intermed. s. flank 14-20 
      DATA FN( 50) /'Intermed. s. flank 14-20 '/
      DATA JVEX(307) / 12/
      DATA JVEX(308) / 46/
      DATA JVEX(309) / 48/
      DATA JVEX(310) / 49/
      DATA JVEX(311) / 21/
      DATA JVEX(312) / 10/
      DATA NAM( 51),NS( 51) /'MSR',313/ !Mauna Loa SW Rift 0-14   
      DATA FN( 51) /'Mauna Loa SW Rift 0-14   '/
      DATA JVEX(313) / 27/
      DATA JVEX(314) / 61/
      DATA JVEX(315) / 32/
      DATA JVEX(316) / 28/
      DATA NAM( 52),NS( 52) /'OLE',317/ !Offshore Lower E.R. 0-14 
      DATA FN( 52) /'Offshore Lower E.R. 0-14 '/
      DATA JVEX(317) / 35/
      DATA JVEX(318) / 81/
      DATA JVEX(319) / 82/
      DATA JVEX(320) / 53/
      DATA JVEX(321) / 45/
      DATA JVEX(322) / 44/
      DATA NAM( 53),NS( 53) /'HIL',323/ !Hilo 0-20 km             
      DATA FN( 53) /'Hilo 0-20 km             '/
      DATA JVEX(323) / 35/
      DATA JVEX(324) / 67/
      DATA JVEX(325) / 80/
      DATA JVEX(326) / 81/
      DATA NAM( 54),NS( 54) /'KEA',327/ !Mauna Kea 0-20 km        
      DATA FN( 54) /'Mauna Kea 0-20 km        '/
      DATA JVEX(327) / 67/
      DATA JVEX(328) / 34/
      DATA JVEX(329) / 33/
      DATA JVEX(330) / 62/
      DATA JVEX(331) / 77/
      DATA JVEX(332) / 79/
      DATA JVEX(333) / 80/
      DATA NAM( 55),NS( 55) /'KOH',334/ !Kohala 0-20 km           
      DATA FN( 55) /'Kohala 0-20 km           '/
      DATA JVEX(334) / 76/
      DATA JVEX(335) / 78/
      DATA JVEX(336) / 79/
      DATA JVEX(337) / 77/
      DATA NAM( 56),NS( 56) /'HUA',338/ !Hualalai 0-20 km         
      DATA FN( 56) /'Hualalai 0-20 km         '/
      DATA JVEX(338) / 62/
      DATA JVEX(339) / 74/
      DATA JVEX(340) / 73/
      DATA JVEX(341) / 76/
      DATA JVEX(342) / 77/
      DATA NAM( 57),NS( 57) /'OHU',343/ !Offshore Hualalai 0-70 km
      DATA FN( 57) /'Offshore Hualalai 0-70 km'/
      DATA JVEX(343) / 72/
      DATA JVEX(344) / 75/
      DATA JVEX(345) / 76/
      DATA JVEX(346) / 73/
      DATA NAM( 58),NS( 58) /'KON',347/ !Kona 0-20 km             
      DATA FN( 58) /'Kona 0-20 km             '/
      DATA JVEX(347) / 32/
      DATA JVEX(348) / 61/
      DATA JVEX(349) / 70/
      DATA JVEX(350) / 74/
      DATA JVEX(351) / 62/
      DATA NAM( 59),NS( 59) /'SKO',352/ !South Kona 0-20 km       
      DATA FN( 59) /'South Kona 0-20 km       '/
      DATA JVEX(352) / 26/
      DATA JVEX(353) / 64/
      DATA JVEX(354) / 71/
      DATA JVEX(355) / 70/
      DATA JVEX(356) / 61/
      DATA JVEX(357) / 27/
      DATA NAM( 60),NS( 60) /'OKO',358/ !Offshore Kona 0-70 km    
      DATA FN( 60) /'Offshore Kona 0-70 km    '/
      DATA JVEX(358) / 70/
      DATA JVEX(359) / 71/
      DATA JVEX(360) / 72/
      DATA JVEX(361) / 73/
      DATA JVEX(362) / 74/
      DATA NAM( 61),NS( 61) /'DKE',363/ !Deep Mauna Kea 20-70 km  
      DATA FN( 61) /'Deep Mauna Kea 20-70 km  '/
      DATA JVEX(363) / 67/
      DATA JVEX(364) / 34/
      DATA JVEX(365) / 33/
      DATA JVEX(366) / 62/
      DATA JVEX(367) / 77/
      DATA JVEX(368) / 79/
      DATA JVEX(369) / 80/
      DATA NAM( 62),NS( 62) /'DKH',370/ !Deep Kohala 20-70 km     
      DATA FN( 62) /'Deep Kohala 20-70 km     '/
      DATA JVEX(370) / 76/
      DATA JVEX(371) / 78/
      DATA JVEX(372) / 79/
      DATA JVEX(373) / 77/
      DATA NAM( 63),NS( 63) /'DHU',374/ !Deep Hualalai 20-70 km   
      DATA FN( 63) /'Deep Hualalai 20-70 km   '/
      DATA JVEX(374) / 62/
      DATA JVEX(375) / 74/
      DATA JVEX(376) / 73/
      DATA JVEX(377) / 76/
      DATA JVEX(378) / 77/
      DATA NAM( 64),NS( 64) /'DKO',379/ !Deep Kona 20-70 km       
      DATA FN( 64) /'Deep Kona 20-70 km       '/
      DATA JVEX(379) / 32/
      DATA JVEX(380) / 61/
      DATA JVEX(381) / 70/
      DATA JVEX(382) / 74/
      DATA JVEX(383) / 62/
      DATA NAM( 65),NS( 65) /'DSK',384/ !Deep South Kona 20-70 km 
      DATA FN( 65) /'Deep South Kona 20-70 km '/
      DATA JVEX(384) / 26/
      DATA JVEX(385) / 64/
      DATA JVEX(386) / 71/
      DATA JVEX(387) / 70/
      DATA JVEX(388) / 61/
      DATA JVEX(389) / 27/
