      SUBROUTINE GETENV (NAME,STR)
C--DUMMY ENVIRONMENT VARIABLE ROUTINE FOR VAX
C--RETURNS A UNIQUE CONTENT OF THE VARIABLE SO HI EXECUTES DEFAULT FILE
      CHARACTER*(*) NAME,STR
      STR='VAX'
      RETURN
      END