      SUBROUTINE HYEDIT (IEDFLG,FILE)
C--RUN AN EDITOR WITHIN HYPOINVERSE. USED TO INTERACTIVELY PROCESS EVENTS.
      CHARACTER FILE*(*)

C--VAX
      IF (IEDFLG.EQ.1) THEN
        CALL EDT$EDIT (FILE)
      ELSE IF (IEDFLG.EQ.2) THEN
        CALL SPAWN (('ED '//FILE))
      END IF

C--SUN/UNIX
C      IF (IEDFLG.EQ.1) THEN
C        CALL SPAWN (('dtpad '//FILE))
C      ELSE IF (IEDFLG.EQ.2) THEN
C        CALL SPAWN (('vi '//FILE))
C      ELSE IF (IEDFLG.EQ.3) THEN
C        CALL SPAWN (('textedit '//FILE))
C      END IF

      RETURN
      END
