      SUBROUTINE HYREP
C--CALLED BY HYPOINVERSE TO REPORT THE CURRENT EVENT ON THE CONSOLE
      INCLUDE 'common.inc'

C--PRINT A HEADING EVERY 15TH LINE
      IT=INUM/15
      IT=INUM-15*IT
      IF (IT.EQ.1) WRITE (6,1000)
1000  FORMAT ('  SEQ ---DATE--- TIME REMARK -LAT-  --LON-  DEPTH  RMS',
     2 ' PMAG  NUM  ERH  ERZ  ID')

      IT=NINT(XLTM)
      IN=NINT(XLNM)
      WRITE (6,1011) INUM,KYEAR2,KMONTH,KDAY, KHOUR,KMIN,REMK,
     2 RMK1,RMK2, LAT,IT,LON,IN, Z1,RMS,PMAG,LABPR,NWR, ERH,ERZ,IDNO
1011  FORMAT (I5,I5,'-',I2,'-',I2, I3,':',I2.2, 1X,A3,
     2 2A1, 2I3,I5,I3, F7.2,F5.2,F5.1,A1,I4, 2F5.1,I10)
      RETURN
      END
