      SUBROUTINE HYTIME (CURTIM)
C--RETURNS THE CURRENT TIME AND DATE AS A 28 CHARACTER STRING
      CHARACTER CURTIM*28

C--SUN/UNIX
      CALL FDATE (CURTIM)

C--VAX
C      CHARACTER DAT*14,TIM*8
C      CALL DATE (DAT)
C      CALL TIME (TIM)
C      CURTIM=(DAT//' , '//TIM//'    ')

C--OS2
C      INCLUDE 'FSUBLIB.FI'
C      INTEGER*2 YEAR, MONTH, DAY, HRS, MINS, SECS, HSECS
C      CALL GETDAT( YEAR, MONTH, DAY )
C      CALL GETTIM( HRS, MINS, SECS, HSECS )
C      WRITE ( CURTIM, 10 ) YEAR, MONTH, DAY, HRS, MINS, SECS, HSECS
C10    FORMAT( I4,'-',I2.2,'-',I2.2,' ',I2.2,':',I2.2,':',I2.2,'.',I2.2,'  ' )

      RETURN
      END
