      SUBROUTINE HYTRL
C--SETS THE TRIAL HYPOCENTER FOR HYPOINVERSE
      INCLUDE 'common.inc'
      KTEMP=30000

C--INCREMENT THE SEQUENCE NUMBER
      INUM=INUM+1

C--DETERMINE EARLIEST ARRIVING STATION AND USE ITS COORDS AS TRIAL LOC
      DO 20 K=1,KSTA
        LSWT=KWT(K)/10
        LPWT=KWT(K)-LSWT*10
        IF (LPWT.GT.3 .OR. KP(K).GT.KTEMP .OR. KPRK(K).EQ.' ')
     2  GO TO 20
        J=KINDX(K)
        KTEMP=KP(K)
20    CONTINUE

C--SET A TRIAL COORDINATE ONLY IF IT WASN'T GIVEN ON INST CARD
      IF (CLAT.EQ.0.) CLAT=JLATD(J)+JLATM(J)/6000.+.005
      IF (CLON.EQ.0.) CLON=JLOND(J)+JLONM(J)/6000.+.005
      IF (T1.EQ.0.) T1=KTEMP/100.-2.
      RETURN
      END
