C--THIS FILE IS INCLUDED BY THE FILE 'common.' WHICH IS INCLUDED BY MOST
C  HYPOINVERSE SUBROUTINES
C--SHORT INTEGER DECLARATIONS FOR HYPOINVERSE. *4 VARIABLES ARE OK, JUST LONGER
C--GENERAL PARAMETERS
      INTEGER*2 IRES, IPADD
C--DATA FOR ALL AVAILABLE STATIONS STORED AS LOOKUP TABLE (SUBSCRIPT J)
      INTEGER*2 JFCOR,JXCOR,JPER,JTYPE,JFGWT
      INTEGER*2 JPSWT,JXWT,JFWT,JLATD,JLATM,JLOND,JLONM,JCAL,JPD
      LOGICAL*2 JLMOD,JFM1,JFM2,JXM1,JXM2,JPM1,JPM2
C  CONDENSED TRAVEL TIMES TO 28 DEPTH & 42 DISTANCE POINTS.
      INTEGER*2 KT,KDHR
C--DATA PRESENT FOR EACH STATION REPORTING AN EVENT (SUBSCRIPT K)
      INTEGER*2 KXWT,KFWT,KINDX,KP,KS,KWT,KFMP,KPER,KCAL,KPAWT
      INTEGER*2 KLSHA,KXMAG,KFMAG,KPMAG,KAMPU,KAMPTYP,KIMTYP
C--DATA PRESENT FOR EACH PHASE (P OR S) REPORTED FOR THIS EVENT (SUBSCRIPT IM)
      INTEGER*2 IND,IMPORT,MTCAL
