
# for GMT3.4.5, use the next two lines
#GGRD_INC_FLAGS = -I$(GMTHOME)/include -I$(NETCDFHOME)/include  -DUSE_GMT3
#GGRD_LIBS_LINKLINE = -lggrd -lgmt -lnetcdf 
# 
#
#
# quad precision
ADD_FLAGS = -DHC_PRECISION=32 
#
# double precision
#ADD_FLAGS = 


GGRD_INC_FLAGS = -I$(GMTHOME)/include -I$(NETCDFDIR)/include 
GGRD_LIBS_LINKLINE = -lggrd -lgmt -lpsl -lnetcdf 
LDFLAGS = -L$(NETCDFDIR)/lib -lnetcdf
