#
# quad precision
#
#ADD_FLAGS = -DHC_PRECISION=32 
#
# double precision
ADD_FLAGS =  -DNO_GMT


# GMT4 
#GGRD_INC_FLAGS = -I$(GMT4HOME)/include -I$(NETCDFDIR)/include -DUSE_GMT4
#GGRD_LIBS_LINKLINE = -lggrd -L$(GMT4HOME)/lib/ -lgmt -lpsl -lnetcdf 
#LDFLAGS = -L$(NETCDFDIR)/lib -lnetcdf
