ARCH=x86_64
HC_HOME=/home/becker/progs/src/seatree/modules/mc/hc
GMTHOME=/usr/local/src/gmt-4.5.14/
NETCDFHOME=/usr/local/src/netcdf-4.3.0/

GGRD_INC_FLAGS = -I$(GMTHOME)/include -I$(NETCDFHOME)/include  
GGRD_LIBS_LINKLINE = -L$(GMTHOME)/lib/ -lggrd -lgmt -lpsl -lnetcdf 

LDFLAGS = -lm

CC = gcc

ADD_FLAGS = -DHC_PRECISION=32 -O2
CFLAGS = -frounding-math -fsignaling-nans  -Werror
