#
# makefile for the solver routines
# 
FC=ifort
FFLAGS=-O2 -m64 -r8 -i8
#FFLAGS=-g -m64 -r8 -i8

SOLVER=zfactor.o back.o factor.o coldot.o unfact.o unback.o

#
../libs/libsolver.a: $(SOLVER)
	$(AR) cr ../libs/libsolver.a  $(SOLVER) 

clean:
	rm -rf core $(SOLVER) 

