#
# makefile for the solver routines
# 

include ../include.gfort64

SOLVER=zfactor.o back.o factor.o coldot.o unfact.o unback.o

#
../libs/libsolver.a: $(SOLVER)
	$(AR) cr ../libs/libsolver.a  $(SOLVER) 

clean:
	rm -rf core $(SOLVER) 

